language: generic

services:
  - docker

env:
  - DEPENDENCY_PACKAGES="meson valac libgee-0.8 libgtk-3-dev python3-pip ninja-build"

install:
  - docker pull ubuntu/docker:xenial-20181005
  - docker run -v "$PWD":/tmp/build-dir ubuntu/docker:xenial-20181005 /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"